using MAT

# Tools for working with smite SMD structures

"""
    mutable struct SMITEsmd 

The `SMITEsmd` struct includes the following fields:

    - `filepath`: The path to the SMD file.
    - `filename`: The name of the SMD file.
    - `varname`: The variable name in the SMD file that contains the data, default is "SMD".
"""
mutable struct SMITEsmd
    filepath::String
    filename::String
    varname::String
end

function SMITEsmd(filepath::String, filename::String)
    return SMITEsmd(filepath, filename, "SMD")
end

"""
    function SMLD2D(smd::SMITEsmd)

Load an SMLD2D structure from a SMITE SMD file specified by a `SMITEsmd` structure.

This function takes a `SMITEsmd` structure, which encapsulates the filepath and filename 
of a SMD file generated by the SMITE (Single Molecule Imaging Toolbox Extraordinaire) 
package. It converts the SMD file into an SMLD2D structure, which is a data structure 
used by the SMLMData package for representing single molecule localization data in 2 dimensions. 

The SMITE package, developed by the Lidke Lab, is a set of tools for the analysis of 
single molecule localization microscopy data. It provides a wide range of components for 
handling, processing, and analyzing such data. The SMD file format is a standard output 
from SMITE and includes single molecule localization information.

# Arguments
- `smd::SMITEsmd`: A `SMITEsmd` structure encapsulating the filepath and filename of the SMD file.

# Returns
- `smld`: An `SMLD2D` structure containing the data from the SMD file.

"""
function SMLD2D(smd::SMITEsmd)
    # load matlab file 
    p = joinpath(smd.filepath, smd.filename)
    file = matopen(p)
    s = read(file, smd.varname) # note that this does NOT introduce a variable ``varname`` into scope
    close(file)

    smld = SMLD2D(
        connectID=Int.(s["ConnectID"])[:],
        x=s["X"][:],
        y=s["Y"][:],
        σ_x=s["X_SE"][:],
        σ_y=s["Y_SE"][:],
        photons=s["Photons"][:],
        σ_photons=s["Photons_SE"][:],
        bg=s["Bg"][:],
        σ_bg=s["Bg_SE"][:],
        framenum=Int.(s["FrameNum"])[:],
        datasetnum=Int.(s["DatasetNum"])[:],
        datasize=Int.([s["YSize"]; s["XSize"]]),
        nframes=Int(s["NFrames"]),
        ndatasets=Int(s["NDatasets"]),
        datafields=(:connectID, :x, :y, :σ_x, :σ_y, :photons, :σ_photons, :bg, :σ_bg, :framenum, :datasetnum)
    )

    return smld
end

"""
    function SMLD3D(smd::SMITEsmd)

Load an SMLD2D structure from a SMITE SMD file specified by a `SMITEsmd` structure.

This function takes a `SMITEsmd` structure, which encapsulates the filepath and filename 
of a SMD file generated by the SMITE (Single Molecule Imaging Toolbox Extraordinaire) 
package. It converts the SMD file into an SMLD2D structure, which is a data structure 
used by the SMLMData package for representing single molecule localization data in 2 dimensions. 

The SMITE package, developed by the Lidke Lab, is a set of tools for the analysis of 
single molecule localization microscopy data. It provides a wide range of components for 
handling, processing, and analyzing such data. The SMD file format is a standard output 
from SMITE and includes single molecule localization information.

# Arguments
- `smd::SMITEsmd`: A `SMITEsmd` structure encapsulating the filepath and filename of the SMD file.

# Returns
- `smld`: An `SMLD3D` structure containing the data from the SMD file.

"""
function SMLD3D(smd::SMITEsmd)
    # load matlab file 
    p = joinpath(smd.filepath, smd.filename)
    file = matopen(p)
    s = read(file, smd.varname) # note that this does NOT introduce a variable ``varname`` into scope
    close(file)

    smld = SMLD2D(
        connectID=Int.(s["ConnectID"])[:],
        x=s["X"][:],
        y=s["Y"][:],
        z=s["Z"][:],
        σ_x=s["X_SE"][:],
        σ_y=s["Y_SE"][:],
        σ_z=s["Z_SE"][:],
        photons=s["Photons"][:],
        σ_photons=s["Photons_SE"][:],
        bg=s["Bg"][:],
        σ_bg=s["Bg_SE"][:],
        framenum=Int.(s["FrameNum"])[:],
        datasetnum=Int.(s["DatasetNum"])[:],
        datasize=Int.([s["YSize"]; s["XSize"]]),
        nframes=Int(s["NFrames"]),
        ndatasets=Int(s["NDatasets"]),
        datafields=(:connectID, :x, :y, :z, :σ_x, :σ_y, :σ_z, :photons, :σ_photons, :bg, :σ_bg, :framenum, :datasetnum)
    )

    return smld
end
