name: TagBot
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:   # Allows manual triggering
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - name: Run TagBot
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DEPLOY_KEY }}  # Optional if using SSH for authentication
